### ISSUE TITLE
Not seeing Response extensions

### ISSUE THREAD

**Issue by jchannon** [adamralph/scriptcs-nancy#113]
I am unable to use `pack.Get("/redirect", _ => Response.AsRedirect("http://google.com"));` as it errors with ` error CS0117: `Nancy.Response' does not contain a definition for `AsRedirect'`

**Comment by adamralph** [comment]
missing `using` statement?

**Comment by jchannon** [comment]
Nope, thats under the Nancy namespace

**Comment by adamralph** [comment]
OK, something weird going on there. We may have an oddity in how the usings work with script packs.

**Comment by adamralph** [comment]
I see the problem. In the code above, `Response` is a reference to the static class `Response`. When you write that same code in a module, `Response` is a reference to the instance property `NancyModule.Response`.

The ambiguity of not enforcing `this.` strikes again (/cc @damianh :wink:).

**Comment by adamralph** [comment]
Try this instead:

```c#
pack.Module(m => m.Get["/redirect"] = _ => m.Response.AsRedirect("http://google.com"));
```

**Comment by adamralph** [comment]
See https://github.com/adamralph/scriptcs-nancy#in-line-routes

**Comment by jchannon** [comment]
I get `ERROR: Script execution failed: (1,14):
<InteractiveExpressionClass>.<Host>m__0(ScriptCs.Nancy.DefaultModule).`

**Comment by adamralph** [comment]
Works for me. Is this mono?

**Comment by jchannon** [comment]
Yup! Happy days :)

**Comment by adamralph** [comment]
Works for me under mono. But on Windows.

**Comment by adamralph** [comment]
Actually no it doesn't. I have exactly the same error.

**Comment by jchannon** [comment]
http://i.giphy.com/UTEwvH9aKvnlC.gif

**Comment by jchannon** [comment]
![](http://media.giphy.com/media/UTEwvH9aKvnlC/giphy.gif)

**Comment by adamralph** [comment]
The mono engine is blowing up on the nested lambda. You can work around it like this

```c#
Action<NancyModule> addRoute = m =>
    m.Get["/redirect"] = _ => m.Response.AsRedirect("http://google.com");
pack.Module(m => addRoute(m));
```

In all honesty, there's little appetite fix things like this in the mono engine at the moment, given that the focus is now to move to the new x-plat Roslyn (https://github.com/scriptcs/scriptcs-engines) so we can dump the Mono engine.

**Comment by jchannon** [comment]
Fair enough.

This also errors for me but not sure why?

`pack.Get("/test", _ => new {Key = "bob"});`

**Comment by adamralph** [comment]
:ok_hand: your diagnosis is spot on. It doesn't like anonymous types and they don't like it.

It only has a small circle of friends.

**Comment by jchannon** [comment]
So how far is the scriptcs roslyn stuff in terms of readiness (if that
makes any sense at all)?

**Comment by adamralph** [comment]
It's close. We're working with @dotnet to close the gaps. You can try it out yourself now, but we don't have it on NuGet yet.

@filipw do you mind chiming in and giving @jchannon instructions for how to try out the new C# engine?

**Comment by adamralph** [comment]
![image](https://cloud.githubusercontent.com/assets/677704/6805817/554f9a72-d245-11e4-804c-dd795c940031.png)

**Comment by adamralph** [comment]
Good luck with the mono compiler... :stuck_out_tongue_winking_eye:

**Comment by jchannon** [comment]
WTF, even MS is X-Plat these days, you guys are so enterprise!

**Comment by filipw** [comment]
Roslyn is not x-plat

**Comment by adamralph** [comment]
Our code is x-plat. But our upstream dep (built by MS) is not..

**Comment by jchannon** [comment]
Bloody MS :smile:

**Comment by adamralph** [comment]
@jchannon I guess I can close this since there's nothing that can be done in the script pack?

You could raise an issue for the mono engine deficiencies over at https://github.com/scriptcs/scriptcs but as I say, it's doubtful they'll get fixed.
